server:
  servlet:
    context-path: /api

logging:
  level:
    br:
      com:
        letscode:
          bookstore:
            service:
              BookService: debug

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./bookstoredb;MODE=MYSQL;AUTO_SERVER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS BOOKSTORE
    username: user
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: BOOKSTORE
        format_sql: true
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console